### ISSUE TITLE
This is cool!

### ISSUE THREAD

**Issue by edglazer** [waynemerricks/rivendell-html#1]
This isn't an issue, so much as a public endorsement! Great idea and thanks for helping to lead the way towards the next iteration of Rivendell!

**Comment by waynemerricks** [comment]
Thanks, I've been busy with work lately but hope to get back to this shortly.

I was testing out wav form displays before work took over, suffice it to say, not as easy as it sounds.

**Comment by edglazer** [comment]
Maybe these will help?
- https://github.com/katspaugh/wavesurfer.js
- "Navigable waveform built on Web Audio and Canvas"
- http://wavesurfer-js.org

and 
- https://github.com/beschulz/wav2json
- Generate waveformjs.org compatible json data out of wav files.
  related:
- https://github.com/beschulz/wav2png/
- Generate waveformjs.org compatible json data out of wav files.

**Comment by waynemerricks** [comment]
Thanks for the links, I have bounced between WAV surfer and a BBC project for which I've forgotten the name.  WAV surfer is probably the one to use.  However, none of these HTML5 web audio components support MP2 files so unless your Riv library is in flat WAV (or custom patched for MP3s) you can't use it.

Flat WAV then means you're pushing large ish files around which is fine on a LAN but not great outside of that.

I was then trying to think around it and the only sensible thing I could come up with was putting something like ffmpeg in between the Riv library to convert to mp3 on the fly.  Obviously it wouldn't be as seamless as using Riv directly without some sort of caching system (10+ seconds to convert most normal songs).

Either way, if I can finish testing WAV surfer and get a custom canvas to replicate rdlibrary -> edit markers it would probably be a useful thing to have.  Lots to do.
